# Centralized pipeline variables for GitHub Actions
# Reference these in your workflow files using the 'vars' context

environment_dev: dev
environment_qa: qa
environment_stage: stage
environment_prod: prod

statefile_key_dev: aro/dev/terraform.tfstate
statefile_key_qa: aro/qa/terraform.tfstate
statefile_key_stage: aro/stage/terraform.tfstate
statefile_key_prod: aro/prod/terraform.tfstate

tfvars_file_dev: environments/dev/terraform.tfvars
tfvars_file_qa: environments/qa/terraform.tfvars
tfvars_file_stage: environments/stage/terraform.tfvars
tfvars_file_prod: environments/prod/terraform.tfvars
